import "@/styles/globals.css";
import { DAppProvider } from "@usedapp/core";
import type { AppProps } from "next/app";
import Head from "next/head";
import { MoralisProvider } from "react-moralis";
import { Share_Tech } from "@next/font/google";
import { dappConfig } from "../utils/dapp";

const shareTech = Share_Tech({ subsets: ["latin"], weight: "400" });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Send ETH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="author" content="@abeltolu" />
      </Head>
      <MoralisProvider initializeOnMount={false}>
        <DAppProvider config={dappConfig}>
          <main className={shareTech.className}>
            <Component {...pageProps} />
          </main>
        </DAppProvider>
      </MoralisProvider>
    </>
  );
}
